/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import Controller.CustomerController;
import Controller.TransactionController;
import Model.ListOfCustomer;
import Model.Transaction;

/**
 *
 * @author Irene Duong
 */
public class CreateTransaction extends javax.swing.JFrame {
        ListOfCustomer list;
        JTable CustomerTable;

        /**
         * Creates new form CreateTransaction
         */
        public CreateTransaction(ListOfCustomer list, JTable CustomerTable) {
                initComponents();
                this.list = list;
                setLocationRelativeTo(null);
                this.CustomerTable = CustomerTable;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                ToField = new javax.swing.JTextField();
                FromField = new javax.swing.JTextField();
                ValueField = new javax.swing.JTextField();
                AddTransacButton = new javax.swing.JButton();
                TypeTranBox = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setText("Transaction");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setText("Type Of Transaction");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setText("Value");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setText("From PhoneNum");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setText("To PhoneNum");

                AddTransacButton.setText("Confirm");
                AddTransacButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddTransacButtonActionPerformed(evt);
                        }
                });

                TypeTranBox.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Send", "Receive From Bank" }));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(45, 45, 45)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                70,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(ToField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                188,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(ValueField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                188,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(FromField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                188,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(TypeTranBox, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(45, 45, 45))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(170, 170, 170)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                105,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(154, 154, 154)
                                                                                                .addComponent(AddTransacButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                93,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                55,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(TypeTranBox,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(43, 43, 43)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(FromField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(47, 47, 47)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ToField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ValueField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(74, 74, 74)
                                                                .addComponent(AddTransacButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(203, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        public void Reload(JTable CustomerTable) {
                DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
                ListOfCustomer list = new ListOfCustomer();
                while (model.getRowCount() != 0) {
                        model.removeRow(0);

                }
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                if (list.getLength() >= 0) {
                        for (int i = 0; i < list.getLength(); i++) {
                                Object[] cus = new Object[] {
                                                list.getListCusi(i).getCusID(),
                                                list.getListCusi(i).getName(),
                                                list.getListCusi(i).getPhoneNum(),
                                                list.getListCusi(i).getAccountNum(),
                                                list.getListCusi(i).getAccountBalance(),
                                                list.getListCusi(i).isGender(),
                                                list.getListCusi(i).getYearBorn(),
                                                list.getListCusi(i).getPassword()
                                };
                                model.addRow(cus);
                        }

                }
        }

        private void AddTransacButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddTransacButtonActionPerformed
                TransactionController tranController = new TransactionController();
                String type = TypeTranBox.getSelectedItem().toString().trim();
                String from = FromField.getText();
                String to = ToField.getText().toString();
                Double value = (double) 0;
                try {
                        value = Double.parseDouble(ValueField.getText());
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Value must be a number and not allow empty");
                }
                tranController.CheckAllField(type, from, to, value);

                Reload(CustomerTable);

        }// GEN-LAST:event_AddTransacButtonActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AddTransacButton;
        private javax.swing.JTextField FromField;
        private javax.swing.JTextField ToField;
        private javax.swing.JComboBox<String> TypeTranBox;
        private javax.swing.JTextField ValueField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        // End of variables declaration//GEN-END:variables
}
