/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.IOException;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import Controller.CustomerController;
import Model.Customer;
import Model.ListOfCustomer;

/**
 *
 * @author Irene Duong
 */
public class CreateForm extends javax.swing.JFrame {
        ListOfCustomer list;
        JTable CustomerTable;

        /**
         * Creates new form CreateForm
         */
        public CreateForm(ListOfCustomer list, JTable CustomerTable) {
                initComponents();
                this.list = list;
                this.CustomerTable = CustomerTable;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Gender = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                NameField = new javax.swing.JTextField();
                PhoneNumberField = new javax.swing.JTextField();
                AccountBalanceField = new javax.swing.JTextField();
                AccountNumberField = new javax.swing.JTextField();
                YearBorn = new javax.swing.JTextField();
                PasswordField = new javax.swing.JPasswordField();
                ButtonMale = new javax.swing.JRadioButton();
                ButtonFemale = new javax.swing.JRadioButton();
                AddButton = new javax.swing.JButton();

                Gender.add(ButtonMale);
                Gender.add(ButtonFemale);

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setText("Name:");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setText("Phone Number:");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setText("Account Balance($):");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setText("Account Number:");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setText("Gender:");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel7.setText("Year Born");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel8.setText("Password");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE)
                                                                                .addComponent(jLabel8,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE))
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addComponent(jLabel2)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel3)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel5)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel4)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jLabel6)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(jLabel7)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel8)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setText("Add New Customer");
                jPanel3.add(jLabel1);

                NameField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NameFieldActionPerformed(evt);
                        }
                });

                PhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PhoneNumberFieldActionPerformed(evt);
                        }
                });

                AccountBalanceField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AccountBalanceFieldActionPerformed(evt);
                        }
                });

                AccountNumberField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AccountNumberFieldActionPerformed(evt);
                        }
                });

                YearBorn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                YearBornActionPerformed(evt);
                        }
                });

                ButtonMale.setText("Male");

                ButtonFemale.setText("Female");
                ButtonFemale.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ButtonFemaleActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(PasswordField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(YearBorn,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(AccountNumberField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(AccountBalanceField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(PhoneNumberField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(NameField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(43, 43, 43)
                                                                                                .addComponent(ButtonMale,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                98,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(84, 84, 84)
                                                                                                .addComponent(ButtonFemale,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                98,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(37, 37, 37)
                                                                .addComponent(NameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(PhoneNumberField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(44, 44, 44)
                                                                .addComponent(AccountNumberField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(AccountBalanceField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(ButtonMale)
                                                                                .addComponent(ButtonFemale))
                                                                .addGap(33, 33, 33)
                                                                .addComponent(YearBorn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(PasswordField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(79, Short.MAX_VALUE)));

                AddButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                AddButton.setText("Add");
                AddButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(AddButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                84,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jPanel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(AddButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 181, Short.MAX_VALUE)))));

                setSize(new java.awt.Dimension(557, 715));
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddButtonActionPerformed
                boolean valid = true;
                String name = NameField.getText();
                String phoneNum = PhoneNumberField.getText();
                String accountNumber = AccountNumberField.getText();

                Double accountBalance = (double) 0;

                int yearBorn = 0;
                // check account Balance
                try {
                        accountBalance = Double.parseDouble(AccountBalanceField.getText());
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Account Balance contains only number");
                        valid = false;
                }
                // check yearBorn
                try {
                        yearBorn = Integer.parseInt(YearBorn.getText());

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "YearBorn must be number");
                        valid = false;

                }

                char[] passwordchar = PasswordField.getPassword();

                boolean gender = true;
                // check which button is selected
                if (ButtonMale.isSelected()) {
                        gender = true;
                } else if (ButtonFemale.isSelected()) {
                        gender = false;
                } else {
                        JOptionPane.showMessageDialog(this, "Please Choose Gender!");
                        valid = false;
                }

                // // checkname
                if (name.matches(".*\\d.*")) {
                        JOptionPane.showMessageDialog(this, "Name should not have numbers!");
                        valid = false;
                }
                // checkPhoneNum
                if (!phoneNum.matches("[0-9]+")) {
                        JOptionPane.showMessageDialog(this, "PhoneNumber must be numbers type!");
                        valid = false;
                }
                // CheckAccountNumber
                if (!accountNumber.matches("[0-9]+")) {
                        JOptionPane.showMessageDialog(this, "AccountNumber must be numbers type!");
                        valid = false;
                }

                // check password
                String password = "";
                if (passwordchar.length == 0) {
                        JOptionPane.showMessageDialog(this, "Password Empty!!!");
                        valid = false;
                } else {
                        for (int i = 0; i < passwordchar.length; i++) {
                                password += passwordchar[i];
                        }
                }
                // if valid= true -> add Customer into List
                if (valid) {
                        CustomerController controller = new CustomerController();
                        controller.ReadFile(list);

                        Customer c = new Customer(name, phoneNum, accountNumber, accountBalance,
                                        gender, password, yearBorn,
                                        list);
                        list.getListCustomer().add(c);

                        controller.WriteFile(list);
                        JOptionPane.showMessageDialog(this, "Create new Customer Successful");

                        setVisible(false);
                        Reload(CustomerTable);
                }

        }// GEN-LAST:event_AddButtonActionPerformed

        public void Reload(JTable CustomerTable) {
                DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
                while (model.getRowCount() != 0) {
                        model.removeRow(0);
                }
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                if (list.getLength() >= 0) {
                        for (int i = 0; i < list.getLength(); i++) {
                                Object[] cus = new Object[] {
                                                list.getListCusi(i).getCusID(),
                                                list.getListCusi(i).getName(),
                                                list.getListCusi(i).getPhoneNum(),
                                                list.getListCusi(i).getAccountNum(),
                                                list.getListCusi(i).getAccountBalance(),
                                                list.getListCusi(i).isGender(),
                                                list.getListCusi(i).getYearBorn(),
                                                list.getListCusi(i).getPassword()
                                };
                                model.addRow(cus);
                        }
                }
        }

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jComboBox1ActionPerformed

        private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NameFieldActionPerformed
                //
        }// GEN-LAST:event_NameFieldActionPerformed

        private void PhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PhoneNumberFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_PhoneNumberFieldActionPerformed

        private void AccountBalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AccountBalanceFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_AccountBalanceFieldActionPerformed

        private void AccountNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AccountNumberFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_AccountNumberFieldActionPerformed

        private void YearBornActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_YearBornActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_YearBornActionPerformed

        private void ButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonFemaleActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_ButtonFemaleActionPerformed

        // </editor-fold>

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField AccountBalanceField;
        private javax.swing.JTextField AccountNumberField;
        private javax.swing.JButton AddButton;
        private javax.swing.JRadioButton ButtonFemale;
        private javax.swing.JRadioButton ButtonMale;
        private javax.swing.ButtonGroup Gender;
        private javax.swing.JTextField NameField;
        private javax.swing.JPasswordField PasswordField;
        private javax.swing.JTextField PhoneNumberField;
        private javax.swing.JTextField YearBorn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        // End of variables declaration//GEN-END:variables
}
