/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.IOException;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import Controller.CustomerController;
import Model.Customer;
import Model.ListOfCustomer;

/**
 *
 * @author Irene Duong
 */
public class EditForm extends javax.swing.JFrame {
        JTable CustomerTable;

        /**
         * Creates new form EditForm
         */
        public EditForm(JTable CustomerTable) {
                initComponents();
                this.CustomerTable = CustomerTable;
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        public void FillForm(Customer c) {
                CusIDField.setText(Integer.toString(c.getCusID()));
                NameField.setText(c.getName());
                PhoneNumberField.setText(c.getPhoneNum());
                AccountBalanceField.setText(Double.toString(c.getAccountBalance()));
                AccountNumberField.setText(c.getAccountNum());
                YearBornField.setText(Integer.toString(c.getYearBorn()));
                boolean gender = c.getGender();
                System.out.println("gendeR:" + gender);
                if (c.getGender() == true) {
                        ButtonMale.setSelected(true);
                } else {
                        ButtonFemale.setSelected(true);
                }
                ;
                PassField.setText(c.getPassword());
        }

        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Gender = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                Name = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                NameField = new javax.swing.JTextField();
                PhoneNumberField = new javax.swing.JTextField();
                AccountBalanceField = new javax.swing.JTextField();
                AccountNumberField = new javax.swing.JTextField();
                ButtonMale = new javax.swing.JRadioButton();
                ButtonFemale = new javax.swing.JRadioButton();
                CusIDField = new javax.swing.JTextField();
                YearBornField = new javax.swing.JTextField();
                PassField = new javax.swing.JTextField();
                UpdateButton = new javax.swing.JButton();

                Gender.add(ButtonMale);
                Gender.add(ButtonFemale);

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("EDIT FORM");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addGap(232, 232, 232)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap(27, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(24, 24, 24)));

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setText("Name:");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setText("Phone Number:");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setText("Account Balance($):");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setText("Account Number:");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel7.setText("Gender:");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel8.setText("Year Born");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel9.setText("Password");

                Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                Name.setText("Customer ID:");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                156, Short.MAX_VALUE)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel8,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel9,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(Name,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(Name)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel4)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel6)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel5)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jLabel7)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(jLabel8)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel9)
                                                                .addContainerGap(251, Short.MAX_VALUE)));

                NameField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NameFieldActionPerformed(evt);
                        }
                });

                PhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PhoneNumberFieldActionPerformed(evt);
                        }
                });

                AccountBalanceField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AccountBalanceFieldActionPerformed(evt);
                        }
                });

                AccountNumberField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AccountNumberFieldActionPerformed(evt);
                        }
                });

                ButtonMale.setText("Male");

                ButtonFemale.setText("Female");
                ButtonFemale.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ButtonFemaleActionPerformed(evt);
                        }
                });

                CusIDField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CusIDFieldActionPerformed(evt);
                        }
                });

                YearBornField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                YearBornFieldActionPerformed(evt);
                        }
                });

                PassField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PassFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(43, 43, 43)
                                                                                                .addComponent(ButtonMale,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                98,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(84, 84, 84)
                                                                                                .addComponent(ButtonFemale,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                98,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(YearBornField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(AccountNumberField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                289,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(AccountBalanceField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                289,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(PhoneNumberField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                289,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(NameField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                289,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(CusIDField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                289,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(PassField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                289,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap(39, Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(CusIDField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23)
                                                                .addComponent(NameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(PhoneNumberField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(AccountNumberField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(AccountBalanceField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(ButtonMale)
                                                                                .addComponent(ButtonFemale))
                                                                .addGap(33, 33, 33)
                                                                .addComponent(YearBornField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(PassField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(78, Short.MAX_VALUE)));

                UpdateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                UpdateButton.setText("Update");
                UpdateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UpdateButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(32, 32, 32)
                                                                                                .addComponent(UpdateButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                84,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jPanel5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jPanel5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(UpdateButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 124, Short.MAX_VALUE)))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void YearBornFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_YearBornFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_YearBornFieldActionPerformed

        private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PassFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_PassFieldActionPerformed

        private void CusIDFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CusIDFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_CusIDFieldActionPerformed

        private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NameFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_NameFieldActionPerformed

        private void PhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PhoneNumberFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_PhoneNumberFieldActionPerformed

        private void AccountBalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AccountBalanceFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_AccountBalanceFieldActionPerformed

        private void AccountNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AccountNumberFieldActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_AccountNumberFieldActionPerformed

        private void YearBornActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_YearBornActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_YearBornActionPerformed

        private void ButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonFemaleActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_ButtonFemaleActionPerformed

        private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpdateButtonActionPerformed
                // Update customer Information after edit
                int cusID = Integer.parseInt(CusIDField.getText());
                String name = NameField.getText();
                String phoneNum = PhoneNumberField.getText();
                String accountNumber = AccountNumberField.getText();
                Double accountBalance = Double.parseDouble(AccountBalanceField.getText());
                int yearBorn = Integer.parseInt(YearBornField.getText());

                String password = PassField.getText();
                boolean genderSelected;
                // check which button is selected
                if (ButtonMale.isSelected()) {
                        genderSelected = true;
                } else {
                        genderSelected = false;
                }
                ListOfCustomer list = new ListOfCustomer();
                CustomerController controller = new CustomerController();

                Customer c = new Customer(name, phoneNum, accountNumber, accountBalance, genderSelected, password,
                                yearBorn,
                                list);
                c.setCusID(cusID);
                controller.Update(cusID, c);
                // announcement success
                JOptionPane.showMessageDialog(this, "Edit Successful");

                setVisible(false);
                //

                // Update
                Reload(CustomerTable);

        }// GEN-LAST:event_UpdateButtonActionPerformed

        public void Reload(JTable CustomerTable) {
                DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
                ListOfCustomer list = new ListOfCustomer();
                while (model.getRowCount() != 0) {
                        model.removeRow(0);

                }
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                if (list.getLength() >= 0) {
                        for (int i = 0; i < list.getLength(); i++) {
                                Object[] cus = new Object[] {
                                                list.getListCusi(i).getCusID(),
                                                list.getListCusi(i).getName(),
                                                list.getListCusi(i).getPhoneNum(),
                                                list.getListCusi(i).getAccountNum(),
                                                list.getListCusi(i).getAccountBalance(),
                                                list.getListCusi(i).isGender(),
                                                list.getListCusi(i).getYearBorn(),
                                                list.getListCusi(i).getPassword()
                                };
                                model.addRow(cus);
                        }

                }
        }

        private void YearBorn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_YearBorn1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_YearBorn1ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField AccountBalanceField;
        private javax.swing.JTextField AccountNumberField;
        private javax.swing.JRadioButton ButtonFemale;
        private javax.swing.JRadioButton ButtonMale;
        private javax.swing.JTextField CusIDField;
        private javax.swing.ButtonGroup Gender;
        private javax.swing.JLabel Name;
        private javax.swing.JTextField NameField;
        private javax.swing.JTextField PassField;
        private javax.swing.JTextField PhoneNumberField;
        private javax.swing.JButton UpdateButton;
        private javax.swing.JTextField YearBornField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        // End of variables declaration//GEN-END:variables
}
