/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.text.DecimalFormat;
import java.time.LocalDate;

import javax.swing.JPanel;

import Controller.CustomerController;
import Model.ListOfCustomer;

/**
 *
 * @author Irene Duong
 */
public class Home extends javax.swing.JPanel {
        ListOfCustomer list;

        /**
         * Creates new form Home
         */
        public Home(ListOfCustomer list) {
                initComponents();
                this.list = list;

        }

        // Create Method to call this from another Panel/Class
        public JPanel getHomeView() {
                totalAccount();
                countAverage();
                countTransaction();

                return HomePanel;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                HomePanel = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                TotalAccountField = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                TotalAccountField1 = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                TotalAccountField2 = new javax.swing.JTextField();

                setPreferredSize(new java.awt.Dimension(900, 900));

                HomePanel.setBackground(new java.awt.Color(30, 30, 30));

                jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/Resources/Icons/icons8_bank_60px.png"))); // NOI18N
                jLabel5.setText("Banking Management Application");
                jLabel5.setAlignmentY(0.0F);
                jLabel5.setFocusable(false);
                jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jPanel1.setBackground(new java.awt.Color(30, 30, 30));

                jPanel2.setBackground(new java.awt.Color(30, 30, 30));

                jLabel1.setBackground(new java.awt.Color(30, 30, 30));
                jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Total Account");

                TotalAccountField.setEditable(false);
                TotalAccountField.setBackground(new java.awt.Color(30, 30, 30));
                TotalAccountField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                TotalAccountField.setForeground(new java.awt.Color(255, 0, 0));
                TotalAccountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                TotalAccountField.setBorder(null);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(46, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addGap(29, 29, 29))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout.createSequentialGroup()
                                                                                                                .addComponent(TotalAccountField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                39,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(60, 60, 60)))));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(40, Short.MAX_VALUE)
                                                                .addComponent(TotalAccountField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel1)
                                                                .addGap(16, 16, 16)));

                jPanel3.setBackground(new java.awt.Color(30, 30, 30));

                jLabel2.setBackground(new java.awt.Color(30, 30, 30));
                jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Total Transaction");

                TotalAccountField1.setEditable(false);
                TotalAccountField1.setBackground(new java.awt.Color(30, 30, 30));
                TotalAccountField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                TotalAccountField1.setForeground(new java.awt.Color(0, 0, 255));
                TotalAccountField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                TotalAccountField1.setBorder(null);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(41, Short.MAX_VALUE)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addContainerGap())
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                                .addComponent(TotalAccountField1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                38,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(49, 49, 49)))));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(40, Short.MAX_VALUE)
                                                                .addComponent(TotalAccountField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2)
                                                                .addGap(16, 16, 16)));

                jPanel4.setBackground(new java.awt.Color(30, 30, 30));

                jLabel3.setBackground(new java.awt.Color(30, 30, 30));
                jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Average Age");

                TotalAccountField2.setEditable(false);
                TotalAccountField2.setBackground(new java.awt.Color(30, 30, 30));
                TotalAccountField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                TotalAccountField2.setForeground(new java.awt.Color(0, 255, 0));
                TotalAccountField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                TotalAccountField2.setBorder(null);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap(36, Short.MAX_VALUE)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel4Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addContainerGap())
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel4Layout.createSequentialGroup()
                                                                                                                .addComponent(TotalAccountField2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                45,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(47, 47, 47)))));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(28, Short.MAX_VALUE)
                                                                .addComponent(TotalAccountField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addGap(16, 16, 16)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(137, 137, 137)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(83, 83, 83)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(278, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(688, Short.MAX_VALUE)));

                javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
                HomePanel.setLayout(HomePanelLayout);
                HomePanelLayout.setHorizontalGroup(
                                HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 511,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                HomePanelLayout.setVerticalGroup(
                                HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(HomePanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                70,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents
         // Create Methods Count Total Account

        public void totalAccount() {
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                int count = list.getLength();
                String text = Integer.toString(count);
                TotalAccountField.setText(text);
        }
        // Create methods Count Total Transaction

        // Create methods Count Average Age
        public void countAverage() {
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                LocalDate currentDate = LocalDate.now();
                int currentYear = currentDate.getYear();
                double averageAge = 0;
                DecimalFormat decimalFormat = new DecimalFormat("#.#");
                if (list.getLength() == 0) {
                        TotalAccountField2.setText("0");

                } else {
                        for (int i = 0; i < list.getLength(); i++) {
                                averageAge += (currentYear - list.getListCusi(i).getYearBorn());
                        }
                        averageAge /= list.getLength();

                        // String text = Double.toString(averageAge);
                        String text = decimalFormat.format(averageAge);
                        TotalAccountField2.setText(text);

                }

        }

        public void countTransaction() {
                CustomerController controller = new CustomerController();
                controller.ReadFile(list);
                int count = 0;
                for (int i = 0; i < list.getLength(); i++) {
                        for (int j = 0; j < list.getListCusi(i).getListTransaction().size(); j++) {
                                count++;
                        }
                }
                String text = Integer.toString(count);
                TotalAccountField1.setText(text);
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel HomePanel;
        private javax.swing.JTextField TotalAccountField;
        private javax.swing.JTextField TotalAccountField1;
        private javax.swing.JTextField TotalAccountField2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        // End of variables declaration//GEN-END:variables
}
